version: "3.9"

services:
  node:
    build: .
    container_name: cardano-plutus
    #command: bash -c "curl -L https://nixos.org/nix/install | sh && . /home/freak/.nix-profile/etc/profile.d/nix.sh"
    volumes:
      - node-db:/node-db
    ports:
      - 3003:3003
      - 9083:9083
  wallet:
    image: inputoutput/cardano-wallet:2021.11.11
    volumes:
      - wallet-testnet-db:/wallet-db
      - node-ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0 --testnet /config/testnet/genesis-byron.json"
    environment:
      NETWORK: "testnet"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      - node

volumes:
  node-db:
  wallet-testnet-db:
  node-ipc: